name: SonarQube Analysis
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Build and Analyze
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dfile.encoding=UTF-8
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify file encoding
        working-directory: ./monitoring-microservice
        run: |
          echo "Verificando encoding de archivos..."
          file -i src/main/resources/application.properties
          file -i pom.xml
          echo "Configuración de encoding:"
          locale

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        working-directory: ./monitoring-microservice
        env:
          MAVEN_OPTS: -Dfile.encoding=UTF-8
        run: |
          mvn -B clean verify \
            -Dfile.encoding=UTF-8 \
            -Dproject.build.sourceEncoding=UTF-8 \
            -Dproject.reporting.outputEncoding=UTF-8 \
            -Dmaven.resources.encoding=UTF-8

      - name: SonarQube Scan
        working-directory: ./monitoring-microservice
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=Carlos-Camacho2003_monitoring-microservice \
            -Dsonar.organization=carlos-camacho2003 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.java.source=21 \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      - name: Verify generated files
        working-directory: ./monitoring-microservice
        run: |
          echo "Verificando archivos generados..."
          file -i target/classes/application.properties
          ls -la target/classes/
