name: SonarQube Analysis
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para análisis preciso de SonarQube

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'  # Distribución recomendada para Java 21
          cache: 'maven'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Verify project structure
        working-directory: ./monitoring-microservice
        run: |
          ls -la
          if [ ! -f pom.xml ]; then
            echo "ERROR: pom.xml not found in monitoring-microservice directory"
            exit 1
          fi

      - name: Build and analyze with SonarQube
        working-directory: ./monitoring-microservice
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para comentarios en PRs
        run: |
          # Construir el proyecto y ejecutar tests
          mvn -B clean verify
          
          # Ejecutar análisis SonarQube
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=Carlos-Camacho2003_monitoring-microservice \
            -Dsonar.organization=carlos-camacho2003 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.java.source=21 \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
